config/routes.rb
Artemys::Application.routes.draw do
  
	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
	devise_for :users

	resources :collection do
		post "sort", on: :collection
	end

	resources :pieces do
		get "edit", on: :collection
		post "upload_photo", on: :collection
	end

	get "be-a-reseller" => "pages#be_a_reseller"
	get "where-to-buy" => "pages#where_to_buy"
	get "gallery" => "gallery#index"
	post "send_contact" => "pages#send_contact"
	get ":action" => "pages"
	root :to => "pages#home"
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :contents, :title
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  has_many :pieces
	def to_param
	  "#{id}-#{title.parameterize}"
	end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_and_belongs_to_many :pieces
	attr_accessible :title
	def to_param
	  "#{id}-#{title.parameterize}"
	end

	attr_accessor :catalogue_path

	def catalogue_url
		case self.title
		when "USA", "Ecuador"
			"https://www.facebook.com/media/set/?set=a.358980027474116.79320.181607861878001&type=3"

		when "Venezuela"
			"https://www.facebook.com/media/set/?set=a.471241669581284.103933.181607861878001&type=3"
		end
	end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :country, :email, :message, :name, :subject
end

app/models/gallery_category.rb
class GalleryCategory < ActiveRecord::Base
  attr_accessible :name
  has_many :gallery_items
end

app/models/gallery_item.rb
class GalleryItem < ActiveRecord::Base
	attr_accessible :image, :image_url, :image_cache, :video, :gallery_category_id, :remove_image
	mount_uploader :image, MediaUploader

	# has_many :media_categorizations
	belongs_to :gallery_category

	attr_accessor :youtube_thumbnail, :youtube_code, :youtube_thumbnail

	def youtube_code
		# /.*v=(.*)&/.match(self.video)[1] || "lol"
		/.*v=(.*)&*/.match(self.video)[1]
		# self.video
	end

	def youtube_pure_video
		"http://www.youtube.com/v/#{self.youtube_code}"
	end

	def youtube_embed
		"<iframe width='560' height='315' src='http://www.youtube.com/embed/#{self.youtube_code}' frameborder='0' allowfullscreen></iframe>".to_html
	end

	def youtube_thumbnail
		"http://img.youtube.com/vi/#{self.youtube_code}/0.jpg"
	end

end

app/models/piece.rb
class Piece < ActiveRecord::Base
	belongs_to :category
	has_and_belongs_to_many :collections
	attr_accessible :image, :watermark, :image_cache, :image_url, :title, :category_id, :remove_image, :collection_ids, :category_id
	mount_uploader :image, PhotoUploader

	after_save :set_code

	# attr_accessor :unique_categories

	# after_update :update_watermark, if: :watermark_changed

	# def watermark_changed
	# 	# Check if the watermark changed
	# 	self.watermark_changed?
	# end

	# def update_watermark
	# 	self.image.recreate_versions!
	# end

	def set_code
		if self.title.blank? and self.image.present?
			title = self.image.path.match(/\/(.*)\./)
			unless title.nil?
				self.title = title[1]
				self.save
			end
		end
	end

	def self.unique_categories
		Category.where(id: [select("DISTINCT category_id").collect(&:category).collect(&:id)]).order("ordem ASC")
	end

	# accepts_nested_attributes_for :collections, :allow_destroy => true
	# attr_accessible :collections_attributes

	rails_admin do
		configure :collections do
			inverse_of :pieces
		end
	end

end

app/models/place.rb
class Place < ActiveRecord::Base
	attr_accessible :city, :country, :localization, :state, :store, :address

	attr_accessor :states

	def self.states
		where("address IS NOT NULL").select("DISTINCT state").collect(&:state)
	end

end

app/models/tags.rb
class Tags < ActiveRecord::Base
  attr_accessible :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController
	def index
	end

	def show
		@collection = Collection.where(title: params[:id]).first
		if @collection
			@pieces = @collection.pieces
			@categorias = @pieces.unique_categories
		end
	end

	def sort
		for sort_params in [params["category-id"], params["piece-id"]] do
			unless sort_params.nil?
				sort_params.each_with_index do |id, ordem|
					the_model = case sort_params
						when params["category-id"] then Category
						when params["piece-id"] then Piece
					end
					the_model.update_all ["ordem = ?", ordem], ["id = ?", id]
				end
			end
		end

		render text: "done"
	end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
	def index
		@category = Category.find_by_title params[:category]
		@media = GalleryItem.all
		
		# @media = if params[:category].nil? then Media.all else Media.where(category_id: @category.id) end
	end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
	def index
		@category = Category.find_by_title params[:category]
		@media = Media.all
		# @media = if params[:category].nil? then Media.all else Media.where(category_id: @category.id) end
	end
end

app/controllers/pages_controller.rb
# encoding: UTF-8
class PagesController < ApplicationController
    def home
    end

    def discover
    end

    def collection
    end

    def gallery
    end

    def where_to_buy
        @states = Place.states
        @places = Place.all
    end
    
    def places
        @states, @cities = {}
        for place in Place.all
            # if place.address.blank? then break end
            @states[place[:state]] ||= {}
            @states[place[:state]][place[:city]] ||= []
            @states[place[:state]][place[:city]] << place 
        end

        respond_to do |format|
            format.json { render :json => @states }
        end
    end

    def contact
    end

    def be_a_reseller

    end

    def send_contact
        @contact = Contact.create params[:contact]
        UserMailer.contact_notification(@contact).deliver
        redirect_to action: "home"
    end

end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
	def show
		@piece = Piece.find params[:id]
		@description = @piece.try("description_#{I18n.locale}".to_sym) || "There isn't a description for this piece yet."
		render layout: "basic"
	end

	def sort
		render json: { status: "success"}
	end

	def edit
		@pieces = Piece.order(:created_at)
	end

	def update
		Piece.find(params[:id]).update_attributes params[:piece]
		render json: params, status: 200
	end

	def upload_photo
		uploaded_file = params["file"]
		p = Piece.new
		p.image = uploaded_file
		p.save
		render json: p, status: "200"
	end

	def edit_multiple
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def menu_items
		["Home", "Discover", "Collection", "Gallery", "Where to buy", "Contact"]
	end
	
	def m(string)
		Maruku.new(string).to_html.html_safe
	end

	def social_media_url(social_media)
		"http://www." + {
			"facebook" => "facebook.com",
			"twitter" => "twitter.com",
			"google-plus" => "googleplus.com"
		}[social_media]
	end
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/layouts/application.html.slim
doctype html
html
	head
		title Artemys
		= stylesheet_link_tag 		"application", :media => "all"
		= javascript_include_tag 	"application", ("sort" unless current_user.nil?)
		= csrf_meta_tags

	body
		- unless current_user.nil?
			= nav_bar brand: "Admin", class: "inverse"
				= menu_group
					= menu_item "Editar peças", edit_pieces_path

		.upper-nav
			.container
				.row					
					.span12
						- for social_media, value in { twitter: "artemys_joyas",
														facebook: "artemysjoyas", 
														youtube: "user/ARTEMYSJN"}

							= link_to image_tag("icon-#{social_media}.png", style:"margin-left: 5px"), "//#{social_media}.com/#{value}"

						.dropdown.pull-right
							= link_to "#", class: "btn btn-inverse dropdown-toggle", data:{toggle:"dropdown"} do
								| Change language
								span.caret
							ul.dropdown-menu
								li= link_to "Español", params.merge(language:"es-VE")
								li= link_to "English", params.merge(language:"en")

		.topo.container
			.row
				.span12
					= link_to image_tag("logo-artemys.png"), "/"
					ul.menu.nav.nav-pills.pull-right
						- for item in menu_items do
							li= link_to (t "menu.#{item.underscore}"), "/#{item.parameterize}"
		- unless params[:action] == "home"
			.container
				ul.breadcrumb
					li.active
						- unless @title.nil? 
							h2= t "titulo.#{@title.underscore}" 
						- else
							= t "titulo."+params[:action].titleize

		= yield
		= render partial: "social/fb_root"
		/.footer.container
				= link_to image_tag("logo-artemys-short.png"), "/"
				ul.menu-footer.nav.nav-pills.pull-right
					- for item in ["Be a reseller", "Where to buy", "Contact"]
						li= link_to item, item.parameterize

app/views/layouts/basic.html.slim
doctype html
html
	head
		title Artemys
		= stylesheet_link_tag 		"application", :media => "all"
		= javascript_include_tag 	"application", ("sort" unless current_user.nil?)
		= csrf_meta_tags

	body style="background-image: none; background-color: transparent"
		= yield

app/views/pages/be_a_reseller.html.slim
.row
	.span12
		h1 home
		p Find me in app/views/pages/home.html.slim

app/views/pages/collection.html.slim
.conteudo.container.well
	.row
		.span12
			h1 Todo

app/views/pages/contact.html.slim
.conteudo.container.well
	.row
		.span6
			= simple_form_for Contact.new, url: "/send_contact", class: "form-horizontal" do |f|
				= f.input :name, 	input_html:{class: "span6"}
				= f.input :email, 	input_html:{class: "span6"}
				= f.input :country, input_html:{class: "span6"}
				= f.input :subject, input_html:{class: "span6"}
				= f.input :message, input_html:{class: "span6", rows: 3}
				= f.submit "Submit", class: "btn btn-primary btn-large span3 pull-right"

		.span6
			.well
				h3 Stay Connected
				ul.icons
					- for social_media in ["Facebook", "Twitter", "Google Plus"]
						li style="vertical-align: center"
							= link_to social_media_url(social_media.parameterize) do
								i class="fa fa-#{social_media.parameterize}-square"
								|  #{social_media}

app/views/pages/discover.html.slim
.conteudo.container.well
	.row
		.span4
			.box-brown style="height: 287px"
				= t "discover.discover artemys"
				= link_to (t "general.read more about"), "#", class: "readmore"
				
		.span4
			.box-brown
				= t "discover.authenticity certificate"
				= link_to (t "general.read more about"), "#", class: "readmore"
				br.clearfix

			.box-beige style="margin-top: 20px"
				= t "discover.press releases"
				= link_to (t "general.read more about"), "#", class: "readmore"

		.span4
			.box-brown
				= t "discover.primary care"
				= link_to (t "general.read more about"), "#", class: "readmore"

			a href="collection.html"
				= image_tag "know-the-pieces.png", height: 114, style: "margin-top: 20px"

app/views/pages/home.html.slim
.container
	.row
		#carousel-home.carousel.slide.span12
			.carousel-inner
				- for banner in %w"Natureza Dia Noite"
					.item class="#{"active" if banner == "Natureza"}"
						= image_tag "banner-#{banner.parameterize}.png"
			= link_to "‹", "#carousel-home", "data-slide" => "prev", class: "carousel-control left"
			= link_to "›", "#carousel-home", "data-slide" => "next", class: "carousel-control right"
	
	.row
		.span12
			ul.thumbnails
				- for logo in ["Latitud Sur", "We Care About the Nature", "American Model Venezuela"]
					li.span4 style="text-align: center"
						= image_tag "logo-#{logo.parameterize}.png"

app/views/pages/places.xml.slim
| <?xml version="1.0"?>
| <?xml-stylesheet href="/eqcenter/catalogs/rssxsl.php?feed=eqs7day-M5.xml" type="text/xsl" media="screen"?>

rss version="2.0" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:dc="http://purl.org/dc/elements/1.1/"
	channel
		title Artemys Stores Locations
		description List based on excel spreadsheet
		link http://www.artemys.com
		dc:publisher hiperativo.co
		pubDate 1/12/12

	- for store in @lojas_venezuela
		- unless store["tienda"].blank? or store["address"].blank?
			item
				pubDate 1/12/12
				title= store["tienda"]
				description= "Located in #{store["local"]} - #{store["Address"]}"
				- @coords = Geocoder.coordinates "#{store["address"]}, #{store["city"]}, #{store["state"]}, Venezuela"
				- if @coords
					geo:lat= @coords[0]
					geo:long= @coords[1]

app/views/pages/where_to_buy.html.slim
= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCiTZFrg9Mn1ZpMp_FiI3631vnQbf6xzkM&sensor=true"

.conteudo.container.well
	.row
		.span12
			form.search-map action="/"
				h3 Quick Search
				.row
					= simple_form_for :location, html: { class: "form-horizontal" } do |f|
						.span3= f.input :country, collection: ["Venezuela"], include_blank: false
						.span3= f.input :state, collection: @states
						.span3= f.input :city, collection: ["Select state first"]

	.row
		.span12
			h3 Places
			ul.thumbnails.places
				- for place in @places
					li.span4.place data-city=place.city
						.thumbnail
							.caption style="height:120px; overflow: auto"
								h4= place.localization || "Sector Centro"
								p.address= place.address
								p.localization= place.localization

app/views/social/_fb_root.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=267159516719712";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>